apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bng-home
  namespace: christopherjmiller
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; navigate-to https:; block-all-mixed-content";
spec:
  tls:
    - hosts:
        - brokenneckgang.com
        - www.brokenneckgang.com
      secretName: bng-home-tls
  rules:
    - host: brokenneckgang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bng-home
                port:
                  number: 80
    - host: www.brokenneckgang.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bng-home
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bng-tls
  namespace: christopherjmiller
spec:
  secretName: bng-home-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: brokenneckgang.com
  dnsNames:
  - brokenneckgang.com
  - www.brokenneckgang.com
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
